/**
 * Curated poster titles for every generator category — concrete visual subjects, not slogans.
 */

'use strict';

const { isTennisBiasedTitle } = require('./sportHobbyTitlePool');
const { isGenericChildrenTitle } = require('./childrenTitlePool');

const CATEGORY_TITLE_POOLS = {
  'botanical': [
    // Ze scalonych kategorii: rosliny z "Japonii" oraz cale "Grzyby i las".
    'Bamboo Grove Light',
    'Maple Leaves Autumn',
    'Wisteria Hanging Bloom',
    'Snow on Pine Branch',
    'Iris Water Garden',
    'Single Chrysanthemum Bloom',
    'Red Toadstool Cap',
    'Fly Agaric Cluster',
    'Fern Frond Unfurling',
    'Moss on Fallen Log',
    'Chanterelle Forest Floor',
    'Birch Bark Detail',
    'Oyster Mushroom Shelf',
    'Pine Cone and Needles',
    'Morel Mushroom Study',
    'Lichen on Stone',
    'Forest Floor Leaves',
    'Puffball in Grass',
    'Mushroom Gills Close',
    'Bracket Fungus Trunk',
    'Woodland Undergrowth Light',
    'Acorn and Oak Leaf',
    'Fern Spiral Detail',
    'Toadstool Ring Meadow',
    'Cherry Blossom Branch',
    'Magnolia Bloom Stem',
    'Wild Flower Bouquet',
    'Peony Petals Soft',
    'Lavender Sprigs Calm',
    'Single Rose Bloom',
    'Cotton Flower Study',
    'Tulip Stem Morning',
    'Delicate Blossom Stem',
    'Spring Branch Buds',
    'Botanical Leaf Detail',
    'Orchid Petal Close',
    'Daisy Chain Meadow',
    'Hydrangea Bloom Soft',
    'Poppy Field Stem',
    // Rozszerzenie 2026-08-03 — konkretne gatunki, po jednym na motyw.
    'Eucalyptus Sprig Grey',
    'Fern Frond Green',
    'Monstera Leaf Split',
    'Palm Leaf Shadow',
    'Sunflower Head Bold',
    'Dahlia Petal Spiral',
    'Ranunculus Layered Bloom',
    'Anemone Dark Centre',
    'Camellia Flower Study',
    'Iris Petal Fall',
    'Protea Bloom Sculptural',
    'Thistle Head Spiky',
    'Wheat Stalks Golden',
    'Pampas Grass Plume',
    'Olive Branch Silver',
    'Willow Branch Trailing',
    'Ginkgo Leaf Fan',
    'Fig Leaf Broad',
    'Ivy Vine Climbing',
    'Snowdrop Early Bloom',
    'Crocus Through Snow',
    'Bluebell Woodland Stem',
    'Foxglove Tall Spire',
    'Sweet Pea Tendril',
    'Jasmine Star Flower',
    'Amaryllis Trumpet Bloom',
    'Calla Lily Curve',
    'Bird of Paradise Bloom',
    'Marigold Ruffled Head',
    'Cactus Spine Detail',
    'Rosehip Winter Branch',
    'Dandelion Seed Ball',
  ],
  'abstract': [
    'Color Field Harmony',
    'Geometric Balance Study',
    'Organic Flow Forms',
    'Chromatic Layer Drift',
    'Silent Shapes Calm',
    'Textured Earth Tones',
    'Vertical Rhythm Lines',
    'Soft Grid Pattern',
    'Layered Arc Forms',
    'Muted Gradient Field',
    'Tonal Block Study',
    'Curved Form Pulse',
    'Earth Tone Layers',
    'Minimal Shape Dance',
  ],
  'nature-landscapes': [
    'Misty Mountain Peak',
    'Forest Morning Mist',
    'Lake Reflection Calm',
    'Rolling Hill Sunset',
    'River Valley Fog',
    'Alpine Meadow Light',
    'Pine Forest Path',
    'Ocean Cliff Horizon',
    'Wheat Field Breeze',
    'Canyon Layered Rock',
    'Waterfall Mist Gorge',
    'Autumn Forest Trail',
    'Highland Moor Silence',
    'Glacier Lake Still',
  ],
  'animals': [
    // Ze scalonej "Japonii" — koi i zuraw to zwierzeta, nie kraj.
    'Koi Carp Turning',
    'Crane in Still Flight',
    'Golden Retriever Portrait',
    'Wild Horse Meadow',
    'Arctic Fox Snow',
    'Barn Owl Wings',
    'African Elephant Study',
    'Red Panda Branch',
    'Swan on Water',
    'Wolf Forest Silhouette',
    'Flamingo Grace',
    'Highland Cow Mist',
    'Sea Turtle Glide',
    'Hummingbird Hover',
    'Deer in Morning Light',
    'Polar Bear Arctic',
    'Butterfly on Flower',
    // Rozszerzenie 2026-08-03. Kierunek podpowiedziany przez sprzedaz: dotychczas
    // wygenerowane plakaty to w wiekszosci portrety konkretnych ras psow i kotow.
    'Beagle Portrait Calm',
    'Dachshund Side Profile',
    'Corgi in Tall Grass',
    'Standard Poodle Elegance',
    'Boxer Dog Portrait',
    'Great Dane Standing',
    'Pug Face Close',
    'Bernese Mountain Dog Snow',
    'Australian Shepherd Gaze',
    'Jack Russell Alert',
    'Cocker Spaniel Ears',
    'Weimaraner Grey Coat',
    'Samoyed Smile Snow',
    'Basset Hound Ears Long',
    'Chow Chow Fluff',
    'Ragdoll Cat Portrait',
    'Bengal Cat Markings',
    'Sphynx Cat Study',
    'Persian Cat Fluff',
    'Siamese Cat Blue Eyes',
    'Norwegian Forest Cat',
    'Scottish Fold Portrait',
    'Russian Blue Cat',
    'Lynx in Winter',
    'European Bison Field',
    'Moose in Shallow Water',
    'River Otter Play',
    // NIE 'Hedgehog in Leaves' — ten tytul zajmuje juz pula "kids-nursery",
    // a handle musi byc unikalny globalnie.
    'Hedgehog Curled Autumn',
    'Grey Heron Standing',
    'Kingfisher on Branch',
    'Atlantic Puffin Cliff',
    'Red Stag Bellow',
    'Brown Hare Field',
    'Red Squirrel Pine',
    'Alpaca Portrait Soft',
    'Peacock Feather Fan',
    'Humpback Whale Dive',
    'Harbour Seal Rock',
    'Chameleon Grip Branch',
    'Tortoise Shell Pattern',
    'Bee on Clover',
  ],
  'cities-travel': [
    // Ze scalonych kategorii: miejsca z "Japonii" oraz cala pula podrozna.
    'Torii Gate at Dawn',
    'Mount Fuji Snow Cap',
    'Zen Garden Ripples',
    'Stone Lantern Moss',
    'Great Wave Curl',
    'Pagoda in Mist',
    'Tea Bowl Still',
    'Red Bridge Reflection',
    'Moon Over Rice Field',
    'Cloud Terraces Mountain',
    'Desert Arch Sunrise',
    'Alpine Peak Ridge',
    'Canyon Layers Deep',
    'Coastal Cliff Wind',
    'Lighthouse on Point',
    'Pine Forest Valley',
    'Glacier Lake Still',
    'Glacier Lagoon Ice',
    'Volcano Slope Dusk',
    'Prairie Road Horizon',
    'Sand Dunes Curve',
    'Waterfall Rock Face',
    'Island Bay Overlook',
    'Redwood Grove Tall',
    'Salt Flat Mirror',
    'Fjord Cliff Water',
    'Mesa at Golden Hour',
    'Highland Moor Mist',
    'Geyser Basin Steam',
    'Paris Skyline Silhouette',
    'Tokyo Night Grid',
    'London Bridge Mist',
    'Manhattan Dawn Skyline',
    'Venice Canal Soft',
    'Barcelona Facade Study',
    'World Map Watercolor',
    'Urban Grid Abstract',
    'Harbor City Lights',
    'Old Town Street Canyon',
    'Berlin Minimal Skyline',
    'Amsterdam Canal Lines',
    'Sydney Opera Silhouette',
    'Prague Rooftop Dawn',
    'Funicular Track Steep',
    'Bicycle Lane Morning',
    'Cafe Chairs Stacked',
    'Ferry Terminal Wait',
    'Bookshop Window Display',
    'Fountain Square Noon',
    'Rail Station Clock',
    'Tiled Metro Wall',
  ],
  'kids-nursery': require('./childrenTitlePool').CHILDREN_TITLE_POOL,
  'space-astronomy': [
    'Saturn Rings Glow',
    'Milky Way Horizon',
    'Crescent Moon Phase',
    'Nebula Color Cloud',
    'Mars Red Sphere',
    'Star Cluster Night',
    'Lunar Surface Crater',
    'Galaxy Spiral Calm',
    'Aurora Borealis Arc',
    'Planet Earth Rise',
    'Jupiter Storm Bands',
    'Comet Tail Streak',
    'Deep Space Silence',
    'Orion Constellation',
    'Solar Eclipse Corona',
    'Meteor Shower Streaks',
    'Radio Dish Array',
    'Asteroid Belt Scatter',
    'Supernova Bloom',
    'Black Hole Lensing',
    'Satellite Panel Wings',
    'Zodiac Light Dawn',
  ],
  'retro-vintage': [
    'Polaroid Camera Still',
    'Vinyl Record Stack',
    'Cassette Tape Warm',
    'Vintage Typewriter Desk',
    'Film Camera Chrome',
    'Retro Radio Cabinet',
    'Sepia Bicycle Lane',
    'Analog Clock Face',
    'Old Suitcase Travel',
    'Rotary Phone Cream',
    'Instant Camera Flash',
    'Tape Deck Buttons',
    'Vintage Sunglasses Case',
    'Retro Lamp Glow',
    'Roller Skate Pair',
    'Pocket Watch Chain',
    'Milk Bottle Crate',
    'Barber Pole Stripe',
    'Sewing Machine Wheel',
    'Analogue Alarm Bells',
  ],
  'vehicles': [
    'Classic Porsche Profile',
    'Motorcycle Chrome Line',
    'Vintage Aircraft Wing',
    'Sailboat Harbor Calm',
    'Rally Car Dust Trail',
    'Speedboat Wake Line',
    'Train Locomotive Steam',
    'Sports Car Curve',
    'Jeep Mountain Trail',
    'Yacht Deck Horizon',
    'Convertible Coastal Road',
    'Helicopter Silhouette Sky',
    'Classic Vespa Scooter',
    'Racing Bicycle Lean',
    'Tram Front Window',
    'Cargo Ship Bow',
    'Sailplane Cockpit',
  ],
  'coffee-tea': [
    'Morning Espresso Cup',
    'Pour Over Coffee Drip',
    'Matcha Bowl Steam',
    'Tea Leaves Spread',
    'Ceramic Teapot Calm',
    'Cappuccino Foam Soft',
    'Coffee Beans Scatter',
    'Earl Grey Steam',
    'Café Latte Morning',
    'French Press Coffee',
    'Iced Coffee Glass',
    'Chai Spice Steam',
    'Moka Pot Brew',
    'Tea Cup Saucer',
    'Cast Iron Kettle',
    'Cafe Window Seat',
    'Sugar Cube Stack',
    'Roaster Drum Detail',
    'Grinder Burr Close',
    'Thermos Flask Steel',
  ],
  'kitchen-food': [
    'Lemon on Linen',
    'Tomato Vine Rustic',
    'Olive Oil Drizzle',
    'Fresh Pasta Nest',
    'Rosemary Herb Bundle',
    'Mediterranean Bread Loaf',
    'Fig and Honey Plate',
    'Avocado Toast Morning',
    'Spice Jar Collection',
    'Pomegranate Seeds Bowl',
    'Basil Pesto Bowl',
    'Saffron Threads Jar',
    'Artichoke Still Life',
    'Mushroom Forest Bundle',
    'Citrus Fruit Bowl',
    'Olive Branch Bowl',
    'Honey Jar Wooden Spoon',
    'Egg Basket Farm',
  ],
  'architecture': [
    'Concrete Brutalist Facade',
    'Spiral Staircase Light',
    'Arched Colonnade',
    'Modern Glass Tower',
    'Brick Archway Shadow',
    'Minimalist Atrium',
    'Bauhaus Window Grid',
    'Cathedral Vault Curve',
    'Urban Bridge Structure',
    'Courtyard Geometry',
    'Art Deco Facade',
    'Brutalist Balcony Grid',
    'Stone Arch Corridor',
    'Chimney Stack Cluster',
    'Wrought Gate Scroll',
    'Terrazzo Floor Detail',
    'Skylight Cross Beams',
    'Portico Step Sequence',
    'Corrugated Metal Fold',
  ],
  'sea-coast': [
    'Calm Wave Shoreline',
    'Dune Grass Wind',
    'Seashell Sand Still',
    'Lighthouse Coast Mist',
    'Turquoise Lagoon Calm',
    'Driftwood Beach Calm',
    'Coastal Cliff Fog',
    'Starfish Tide Pool',
    'Sailboat Horizon Line',
    'Beach Pebble Pattern',
    'Soft Sand Ripples',
    'Harbor Buoy Morning',
    'Misty Coastal Path',
    'Kelp Forest Sway',
    'Breakwater Concrete Blocks',
    'Oyster Shell Cluster',
    'Estuary Channel Curve',
    'Cormorant Wings Dry',
    'Sailing Knot Detail',
    'Anchor Chain Links',
  ],
  'sports-hobbies': require('./sportHobbyTitlePool').SPORT_HOBBY_TITLE_POOL,
  'gaming-esports': [
    'Neon Controller Glow',
    'Retro Arcade Cabinet',
    'Gaming Headset Setup',
    'Pixel Heart Icon',
    'Cyber Arena Lights',
    'Mechanical Keyboard Mood',
    'Racing Wheel Desk',
    'VR Headset Silhouette',
    'Arcade Joystick Red',
    'Esports Arena Beam',
    'Neon Gaming Desk',
    'Retro Game Cartridge',
    'Dice Set Scatter',
    'Chess Endgame Board',
    'Loading Bar Abstract',
    'Sprite Grid Pattern',
    'Console Vent Lines',
    'Trading Card Fan',
    'Score Counter Digits',
    'Level Map Isometric',
    'Cable Management Wall',
  ],
  'ai-technology': [
    'Neural Network Mesh',
    'Data Stream Lines',
    'Robot Hand Grace',
    'Circuit Board Pattern',
    'Futuristic Chip Glow',
    'Digital Brain Nodes',
    'Hologram Grid Light',
    'Quantum Wave Form',
    'Server Rack Blue',
    'AI Chip Abstract',
    'Fiber Optic Pulse',
    'Binary Flow Field',
    'Silicon Wafer Disc',
    'Cooling Fins Array',
    'Punch Card Rhythm',
    'Motherboard Topography',
    'Terminal Cursor Blink',
  ],
  'humor-memes': [
    'Cat in Cardboard Box',
    'Dog with Glasses',
    'Llama Drama Face',
    'Penguin Waddle Walk',
    'Capybara Chill Pond',
    'Shiba Inu Smile',
    'Bear Coffee Morning',
    'Frog on Lily Pad',
    'Goose Chase Scene',
    'Owl Reading Book',
    'Raccoon Trash Can',
    'Sloth Hanging Branch',
    // Rozszerzenie 2026-08-03. Humor sytuacyjny, bez tekstu i bez znanych postaci —
    // zgodnie z zakazami w trybie promptu tej kategorii.
    'Cat Judging Silently',
    'Duck in Rain Boots',
    'Pigeon on Statue Head',
    'Cow Wearing Daisy Crown',
    'Squirrel Guarding Acorn',
    'Hedgehog in Teacup',
    'Alpaca Bad Haircut',
    'Pug in Knitted Sweater',
    'Sheep in Sunglasses',
    'Goat on Car Roof',
    'Crow Stealing Something Shiny',
    'Otter Holding Favourite Rock',
    'Chicken Avoiding Puddle',
    'Turtle Racing Snail',
    'Rabbit in Sunglasses',
    'Parrot Side Eye',
    'Seagull Chip Theft',
    'Flamingo Standing Awkward',
    'Toad on Mushroom Stool',
    'Fox in Rubber Boots',
    'Bear in Hammock',
    'Cat on Warm Keyboard',
    'Dog Head Out Window',
    'Highland Cow Bad Fringe',
  ],
  'cyberpunk-neon': [
    'Neon Alley Rain',
    'Cyber City Night',
    'Holographic Billboard',
    'Rainy Street Pink',
    'Futuristic Motorcycle Neon',
    'Tokyo Neon Crosswalk',
    'Glitch Skyline Purple',
    'Laser Grid Tunnel',
    'Chrome Mask Portrait',
    'Neon Sign Reflection',
    'Cyber Rain Umbrella',
    'Electric Skyline Blue',
    'Vending Machine Row',
    'Monorail Overpass',
    'Data Tower Spire',
    'Circuit Tattoo Arm',
    'Hover Bike Parked',
    'Split Screen Static',
    'Rooftop Antenna Field',
    'Underpass Light Strip',
  ],
  'music-sound': [
    'Acoustic Guitar Wood',
    'Vinyl Record Spin',
    'Piano Keys Close',
    'Jazz Trumpet Brass',
    'Drum Kit Stage',
    'Microphone Studio',
    'Saxophone Golden Light',
    'Headphones on Vinyl',
    'Violin Scroll Detail',
    'Cassette Mixtape Mood',
    'Electric Bass Curve',
    'Turntable Needle Drop',
    'Mixing Desk Faders',
    'Concert Hall Seats',
    'Sheet Music Stack',
    'Harp String Fan',
    'Accordion Bellows Fold',
    'Amplifier Grille Cloth',
    'Metronome Steady Beat',
    'Choir Loft Organ Pipes',
  ],
  'wellness-yoga': [
    'Yoga Mat Morning',
    'Meditation Cushion Calm',
    'Spa Stones Stack',
    'Linen Towel Fold',
    'Herbal Tea Ritual',
    'Lotus Pose Silhouette',
    'Essential Oil Drop',
    'Bamboo Forest Zen',
    'Candle and Crystals',
    'Breath and Light',
    'Morning Stretch Calm',
    'Salt Lamp Glow',
    'Singing Bowl Rim',
    'Eucalyptus Shower Bundle',
    'Breathing Circle Study',
    'Dry Brush Bristles',
    'Incense Smoke Curl',
    'Cold Plunge Surface',
    'Mala Beads Coil',
  ],
  'symbols-sacred-geometry': [
    'Yin Yang Balance',
    'Mandala Geometry',
    'Lotus Flower Zen',
    'Sacred Geometry Gold',
    'Moon Phase Cycle',
    'Tree of Life Line',
    'Zen Enso Circle',
    'Celtic Knot Interlace',
    'Om Symbol Engraved',
    'Sri Yantra Triangles',
    'Metatron Cube Grid',
    'Seed of Life Circles',
    'Lotus Mandala Rings',
    'Flower of Life Grid',
    'Chakra Color Wheel',
    'Sun Moon Balance',
    'Golden Spiral Curve',
    'Platonic Solid Study',
    'Vesica Piscis Overlap',
    'Torus Ring Section',
    'Fractal Branch Order',
    'Hexagon Tiling Field',
    'Triangle Nest Descent',
    'Orbit Ellipse Layers',
  ],
  // Pule dla kategorii dodanych 2026-08-03.
  // Zasada: JEDEN tytul na motyw. Dzieki temu tasowanie samo rozklada tematy
  // i nie trzeba blokady stronniczosci, jak przy tenisie w sports-hobbies.

  // Pule dla osmiu kategorii dolozonych pod rynek niemiecki.
  'typography-quotes': [
    'Good Morning Lettering',
    'Stay Wild Script',
    'Hello Sunshine Type',
    'Home Sweet Home Type',
    'Bloom Where Planted',
    'Slow Living Words',
    'One Word Breathe',
    'Coffee First Lettering',
    'Wander More Type',
    'Be Here Now Words',
    'Kind Words Poster',
    'Do Less Better',
    'Rise And Shine Type',
    'Everyday Magic Words',
    'Quiet Mind Lettering',
    'Choose Joy Script',
    'Fresh Start Letters',
    'Hold The Line Type',
    'Enjoy Small Things',
    'Grow Through It',
  ],
  'mountains-hiking': [
    'Alpine Ridge Morning',
    'Summit Cairn Stone',
    'Mountain Hut Dusk',
    'Glacier Tongue Ice',
    'Trail Marker Post',
    'Rope And Carabiner',
    'Hiking Boots Rest',
    'Valley Fog Below',
    'Dolomite Spires Light',
    'Snow Cornice Edge',
    'Switchback Trail Lines',
    'Peak Silhouette Layers',
    'Mountain Stream Crossing',
    'Alpine Meadow Path',
    'Rock Face Texture',
    'Summit Sunrise Glow',
    'Ridge Walk Shadows',
    'Mountain Lake Basin',
  ],
  'line-art-figures': [
    'Single Line Portrait',
    'Resting Hands Study',
    'Two Faces Meeting',
    'Contour Torso Study',
    'Embrace In One Line',
    'Profile And Petal',
    'Seated Figure Lines',
    'Hand Holding Stem',
    'Abstract Face Curve',
    'Back And Shoulders',
    'Dancer In Motion',
    'Linked Hands Study',
    'Reclining Form Line',
    'Shoulder And Neck',
    'Continuous Face Loop',
    'Woman And Leaf',
    'Gesture Study Lines',
    'Folded Arms Contour',
  ],
  'bar-cocktails': [
    'Coupe Glass Reflection',
    'Negroni Orange Twist',
    'Shaker And Strainer',
    'Ice Cube Close',
    'Martini Olive Skewer',
    'Citrus Peel Curl',
    'Whiskey Amber Glow',
    'Bar Counter Evening',
    'Highball Bubbles Rising',
    'Espresso Martini Foam',
    'Gin Botanicals Study',
    'Beer Head Pour',
    'Coupe Stack Still',
    'Bitters Bottle Row',
    'Lime Wedge Detail',
    'Vermouth Golden Hour',
    'Cocktail Cherry Drop',
    'Copper Jigger Shine',
  ],
  'zodiac-astrology': [
    'Leo Constellation Chart',
    'Scorpio Star Lines',
    'Aquarius Water Bearer',
    'Taurus Bull Diagram',
    'Libra Balance Scales',
    'Pisces Twin Fish',
    'Gemini Twins Chart',
    'Virgo Wheat Sheaf',
    'Aries Ram Horns',
    'Cancer Crab Shell',
    'Sagittarius Arrow Arc',
    'Capricorn Sea Goat',
    'Zodiac Wheel Complete',
    'Sun And Moon Chart',
    'Celestial Map Ornament',
    'Birth Chart Circle',
    'Star Sign Constellation',
    'Lunar Phase Diagram',
    'Astrolabe Ring Detail',
  ],
  'fitness-gym': [
    'Dumbbell Rack Order',
    'Kettlebell Shadow Study',
    'Boxing Gloves Hanging',
    'Barbell Plate Stack',
    'Running Form Silhouette',
    'Jump Rope Coil',
    'Gym Chalk Hands',
    'Weight Bench Empty',
    'Sprinter Start Block',
    'Rowing Stroke Motion',
    'Medicine Ball Rest',
    'Pull Up Bar',
    'Squat Rack Lines',
    'Skipping Rope Blur',
    'Athletic Shoe Study',
    'Training Timer Face',
    'Grip And Bar',
    'Cable Machine Lines',
    'Climbing Holds Wall',
    'Treadmill Belt Lines',
    'Water Bottle Steel',
    'Locker Door Row',
    'Resistance Band Loop',
    'Stopwatch Lap Button',
  ],
  'fashion-beauty': [
    'Perfume Bottle Light',
    'Lipstick Bullet Study',
    'Stiletto Heel Profile',
    'Handbag Chain Detail',
    'Silk Fold Study',
    'Pearl Strand Curve',
    'Dressing Table Morning',
    'Fashion Figure Sketch',
    'Powder Compact Open',
    'Mascara Wand Detail',
    'Trench Coat Belt',
    'Sunglasses On Marble',
    'Nail Polish Drop',
    'Hair Comb Study',
    'Ribbon And Lace',
    'Vanity Mirror Glow',
    'Scarf Knot Detail',
    'Earring Drop Shine',
    'Tailor Chalk Marks',
    'Button Card Display',
    'Tweed Weave Close',
    'Glove Leather Seam',
  ],
  'love-romance': [
    'Two Hands Entwined',
    'Embrace In Shadow',
    'Shared Coffee Morning',
    'Anniversary Ring Study',
    'Couple Silhouette Dusk',
    'Kiss In One Line',
    'Heart In Sand',
    'Together Since Lines',
    'Love Letter Fold',
    'Dancing Close Pair',
    'Two Cups Waiting',
    'Intertwined Fingers Study',
    'Forehead Touch Study',
    'Paper Heart Fold',
    'Walking Hand In Hand',
    'Whispered Secret Pair',
    'Balcony Embrace Evening',
    'Rose And Hand',
    'Envelope Wax Seal',
    'Bench Under Tree',
    'Ribbon Bow Knot',
    'Candlelit Table Setting',
    'Pressed Flower Book',
  ],
  'club-orzel': [
    // Tytuly po POLSKU — jedyna kategoria z polskojezycznym klientem.
    'Herb Klubu na Zielonym',
    'Stadion pod Światłami',
    'Piłka na Murawie o Świcie',
    'Szalik na Trybunie',
    'Rożna Chorągiewka',
    'Siatka Bramki z Bliska',
    'Korki na Trawie',
    'Boisko o Poranku',
    'Trybuna Pełna Ludzi',
    'Piłka w Siatce',
    'Murawa po Deszczu',
    'Wejście na Boisko',
    'Zielono-Złote Barwy',
    'Osiemdziesiąt Lat Klubu',
    'Karkonosze nad Boiskiem',
    'Klubowa Szatnia',
    'Puchar w Gablocie',
    'Mecz w Mysłakowicach',
  ],
};

/** Slogan patterns that produce vague non-visual titles per category. */
const GLOBAL_GENERIC_PATTERNS =
  /\b(symphony|whispers of|serenity alone|dreams$|magic moments|vibes$|bliss$|wonder$|odyssey$)\b/i;

const CATEGORY_GENERIC_PATTERNS = {
  'kids-nursery': /\b(happy times|fun adventure|colorful dreams|play zone|joy ride)\b/i,
  'sports-hobbies': /\b(go team|game day|champion|victory vibes|athletic spirit)\b/i,
  'botanical': /\b(green vibes|plant love|nature's art|botanical beauty)\b/i,
  'abstract': /\b(abstract balance|color pulse alone)\b/i,
};

function normalizeTitleKey(title) {
  return String(title || '').trim().toLowerCase();
}

function isGenericCategoryTitle(category, title) {
  const cat = String(category || '').trim();
  const t = String(title || '').trim();
  if (!t) return true;
  if (GLOBAL_GENERIC_PATTERNS.test(t)) return true;
  const pat = CATEGORY_GENERIC_PATTERNS[cat];
  if (pat && pat.test(t)) return true;
  if (cat === 'kids-nursery' && isGenericChildrenTitle(t)) return true;
  if (cat === 'sports-hobbies' && isTennisBiasedTitle(t)) return false; // filtered at pick time
  return false;
}

function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function hasCuratedTitlePool(category) {
  const pool = CATEGORY_TITLE_POOLS[String(category || '').trim()];
  return Array.isArray(pool) && pool.length > 0;
}

/**
 * @param {string} category
 * @param {number} count
 * @param {string[]} excludeTitles
 * @returns {string[]}
 */
function pickCategoryTitles(category, count, excludeTitles = []) {
  const cat = String(category || '').trim();
  const pool = CATEGORY_TITLE_POOLS[cat];
  if (!pool || !pool.length) return [];

  const n = Math.max(1, Number(count) || 1);
  const exclude = new Set((excludeTitles || []).map(normalizeTitleKey));
  const candidates = shuffle(
    pool.filter((t) => !exclude.has(normalizeTitleKey(t)) && !isGenericCategoryTitle(cat, t))
  );

  const picks = [];
  let tennisCount = 0;
  for (const title of candidates) {
    if (picks.length >= n) break;
    if (cat === 'sports-hobbies') {
      const tennis = isTennisBiasedTitle(title);
      if (tennis && tennisCount >= 1) continue;
      if (tennis) tennisCount += 1;
    }
    if (picks.some((x) => normalizeTitleKey(x) === normalizeTitleKey(title))) continue;
    picks.push(title);
  }
  return picks;
}

function filterValidCategoryTitles(category, titles, excludeTitles = []) {
  const cat = String(category || '').trim();
  const exclude = new Set((excludeTitles || []).map(normalizeTitleKey));
  const out = [];
  let tennisCount = 0;
  for (const raw of titles || []) {
    const t = String(raw || '').trim();
    if (!t || exclude.has(normalizeTitleKey(t))) continue;
    if (isGenericCategoryTitle(cat, t)) continue;
    if (out.some((x) => normalizeTitleKey(x) === normalizeTitleKey(t))) continue;
    if (cat === 'sports-hobbies' && isTennisBiasedTitle(t)) {
      if (tennisCount >= 1) continue;
      tennisCount += 1;
    }
    out.push(t);
  }
  return out;
}

module.exports = {
  CATEGORY_TITLE_POOLS,
  hasCuratedTitlePool,
  pickCategoryTitles,
  filterValidCategoryTitles,
  isGenericCategoryTitle,
  normalizeTitleKey,
};
